### PR TITLE
Add Texas data

### LINKED ISSUE #53: Add Texas data for 2012, 2014, 2016 and 2018
See #1

### PR DESCRIPTION
**Pull request by chriszs**
Here's the Texas data. See included README for details.

### CODE REVIEW

**Comment by chriszs** [comment]
Have been comparing this to 2012 data from Secretary of State. Ours is currently far more complete (theirs has 2,272 usable records, 1,973 with addresses, versus 6,492 and theoretically all with some sort of address, the major difference is they didn't include most of the large counties), but there are a couple small counties they have that we're missing and a couple small discrepancies I want to better understand or resolve. Expect 2016 comparison to be similar. And while I'm at it, I'm looking at 2018 data as well.

**Comment by pratheekrebala** [comment]
Thanks Chris! How are the Precinct Name/ID columns on the state-wide data? I'm guessing the county level data has more useful info?

**Comment by chriszs** [comment]
For 2012, the SoS has a column called "home precinct" that seems consistently filled in with one number. Whether that accounts for consolidation/combined precincts and how, I'm not sure. For those 2,200 records it's more consistently available than in our data, but it'd be difficult to merge the two data sets because nothing else is exactly the same. 2016 has the same column, but adds a "work precinct" column that seems more optional. I'm inclined to stick with the precincts we entered, since our data is otherwise more consistent and complete.

**Comment by chriszs** [comment]
Added more 2016 data from the Secretary of State, fixed a couple issues.

**Pull request closed without merging**
